-- Citizen Portal: citizen submission + admin verification schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.submitted_opportunities (
  id bigint generated by default as identity primary key,
  title text,
  name text,
  category text not null,
  description text,
  detail text,
  extra_data jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  verification_status text not null default 'pending',
  source_type text not null default 'user_submitted',
  created_at timestamptz not null default now()
);

alter table public.submitted_opportunities add column if not exists title text;
alter table public.submitted_opportunities add column if not exists name text;
alter table public.submitted_opportunities add column if not exists category text;
alter table public.submitted_opportunities add column if not exists description text;
alter table public.submitted_opportunities add column if not exists detail text;
alter table public.submitted_opportunities add column if not exists extra_data jsonb not null default '{}'::jsonb;
alter table public.submitted_opportunities add column if not exists status text not null default 'pending';
alter table public.submitted_opportunities add column if not exists verification_status text not null default 'pending';
alter table public.submitted_opportunities add column if not exists source_type text not null default 'user_submitted';
alter table public.submitted_opportunities add column if not exists created_at timestamptz not null default now();

create index if not exists idx_submitted_opportunities_status on public.submitted_opportunities(status);
create index if not exists idx_submitted_opportunities_category on public.submitted_opportunities(category);

-- Recommended RLS policy for the anon frontend: citizens can submit, but cannot
-- approve/reject. Admin review is performed through the FastAPI backend.
alter table public.submitted_opportunities enable row level security;

drop policy if exists "citizens can submit opportunities" on public.submitted_opportunities;
create policy "citizens can submit opportunities"
on public.submitted_opportunities
for insert
to anon, authenticated
with check (status = 'pending' and verification_status = 'pending');

-- Ensure the existing public opportunities table can receive verified records.
-- These columns are harmless if they already exist.
alter table public.opportunities add column if not exists verification_status text;
alter table public.opportunities add column if not exists source_type text;
